// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SIMDArray")>]
[<assembly: AssemblyProductAttribute("SIMDArray")>]
[<assembly: AssemblyDescriptionAttribute("SIMD enhanced Array operations for F#")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SIMDArray"
    let [<Literal>] AssemblyProduct = "SIMDArray"
    let [<Literal>] AssemblyDescription = "SIMD enhanced Array operations for F#"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
