name: Build and Publish
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install tools
      run: dotnet tool restore
    - name: Build and Test
      run: dotnet test -c Release
    - name: Pack
      run: dotnet pack -c Release
    - name: Build docs
      run: dotnet fsdocs build --properties Configuration=Release
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
    - name: Publish NuGets (if this version not published before)
      run: dotnet nuget push src/SIMDArray/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_ORG_TOKEN_2022 }} --skip-duplicate

# NUGET_ORG_TOKEN_2022 is listed in "Repository secrets" in https://github.com/fsprojects/SIMDArray/settings/secrets/actions
